# Step 1: Authenticate the user
POST https://examcell.rguktn.ac.in/results/202324_20E2_S2_Reg/authenticate_user.php
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Cookie: PHPSESSID=8i9tfr0ud8ahh1e1lnpbiukfr3
Referer: https://examcell.rguktn.ac.in/results/202324_20E2_S2_Reg/
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
X-Requested-With: XMLHttpRequest

token=j5tnBq71wx8hs69hbov5hTBJhYE1vEdzk6HbvJICZBDDxj6uRfzuAio122DTM+8rvURAwXp9hrLDyg==

# Assuming successful authentication, copy the token from the response and use it in the next request
###
# Step 2: Get the result (use the actual token obtained from the previous step)
POST https://examcell.rguktn.ac.in/results/202324_20E2_S2_Reg/getResult.php
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Cookie: PHPSESSID=98u4c01ub0bk3q490ios6bf0o7
Referer: https://examcell.rguktn.ac.in/results/202324_20E2_S2_Reg/
# User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
# X-Requested-With: XMLHttpRequest

SID=N200212&token=Ze5hXOqjPm2sIIwXx2EF6v3vX9d10wFYJWyF6vD764NcBLAxfrA73Upm7k5FljvS2kizMmeVVF25eQ==
###

POST https://freighteg.in/freightapi/ULLIPtracking
Content-Type: application/json

{
  "company_id": "665580f353ccced94082681b",
  "tracking_For": "VAHAN",
  "parameters": {
    "vehiclenumber": "HR55AQ5994"
  }
}



###
POST https://freighteg.in/freightapi/ULLIPtracking
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJxaWtfdXNyIiwiaWF0IjoxNzIxODQwMDI0LCJhcHBzIjoiZGF0YXB1c2gifQ.seQnFT3tjqPfsEPo34eSP-HQi4W8vGvPAwFuW910Y3Sw1mlbgMnLp89VKL9xB9coX2Yf8GvPYmvtjwSPkLx9GQ

{
  "company_id": "665580f353ccced94082681b",
  "tracking_For": "SARATHI",
  "parameters": {
    "dlnumber": "AP03020190043439",
    "dob": "1980-09-10"
  }
}


###
### Get Plans
GET https://fastagtracking.com/customulip/plans
Content-Type: application/json

####

### Login Request
### Login Request
POST https://fastagtracking.com/customulip/login
Content-Type: application/json

{
    "phone": "1234567890",
    "password": "password"
}




POST https://fastagtracking.com/company


# {
#   "name": "Siddhu",
#   "phone": "939884815",
#   "password": "its password",
#   "plan": "66b0fa931ec9b8fa74ae795b",
#   "expiryDate": "2024-12-31T23:59:59.999Z"
# }
### Create a new company
POST https://fastagtracking.com/customulip/company
Content-Type: application/json

{
    "name": "Company Name",
    "phone": "1234567890",
    "password": "password",
    "plan": "66b0fa931ec9b8fa74ae795b",
    "expiryDate": "2024-12-31T23:59:59Z",
    "vehicleNumbers": ["ABC1234"]
}

### Get all companies
GET https://fastagtracking.com/customulip/company

### Get a specific company by ID
GET https://fastagtracking.com/customulip/company/66b0faebbd10f1fc2ec12b8d

### Update a specific company by ID
PUT https://fastagtracking.com/customulip/company/66c5c7b3811b9657c7b7c8ca
Content-Type: application/json

{
    "name": "Company2",
    "phone": "9398848215",
    "maxApiHit":10000,
    "expiryDate":"2025-09-05T10:55:47.486Z"
}

### Get all plans
GET https://fastagtracking.com/customulip/plans

### Login
POST https://fastagtracking.com/customulip/login
Content-Type: application/json

{
    "phone": "1234567890",
    "password": "password"
}

### Delete a specific company by ID
DELETE https://fastagtracking.com/customulip/company/{company_id}

### ULIP API
POST https://fastagtracking.com/customulip/ulipApi
Content-Type: application/json

{
    "company_id": "66b5974fc5f0a6f365cc32ea",
    "tracking_For": "FASTAG",
    "parameters": { 
        "vehiclenumber": "ABC1234"
    }
}

###
### Fastag Tracking API Request
POST https://fastagtracking.com/customulip/ulipApi
Content-Type: application/json

{
    "company_id": "66b5974fc5f0a6f365cc32ea",
    "tracking_For": "FASTAG",
    "parameters": { "vehiclenumber": "HR55AL7405" }
}

###
POST  https://fastagtracking.com/customulip/pay

{
    "company_id": "66b5974fc5f0a6f365cc32ea",
    "a": "FASTAG",
    "parameters": { "vehiclenumber": "HR55AL7405" }
}
###

POST https://fastagtracking.com/customulip/pay
Content-Type: application/json
# Authorization: Bearer <your_token_here>  # If authentication is required

{
    "company_id": "66b5974fc5f0a6f365cc32ea",
    "amount": 100,  
    "phone": "9398848215"
}

###
GET https://fastagtracking.com/customulip/pay?company_id=66b5974fc5f0a6f365cc32ea&amount=149000&phone=9398848215
# Content-Type: application/json
# Authorization: Bearer <your_token_here>  # If authentication is required

####
PUT https://fastagtracking.com/customulip/trip/66e494073060b3d201c40e9f
Content-Type: application/json

{
  "Completed": true
}

###
GET https://fastagtracking.com/customulip/update-location-history/


###
DELETE https://fastagtracking.com/customulip/trip/66e7ca36b07b38507c138ddb


