### Create a new company
POST https://fastagtracking.com/customulip/company
Content-Type: application/json
{
    "name": "Company Name",
    "phone": "1234567890",
    "password": "password",
    "plan": "66b0fa931ec9b8fa74ae795b",
    "expiryDate": "2024-12-31T23:59:59Z",
    "vehicleNumbers": ["ABC1234"]
}


### Get all companies
GET https://fastagtracking.com/customulip/company

### Get a specific company by ID
GET https://fastagtracking.com/customulip/company/66b0faebbd10f1fc2ec12b8d

### Update a specific company by ID
PUT https://fastagtracking.com/customulip/company/66b0faebbd10f1fc2ec12b8d
Content-Type: application/json

{
    "name": "Company2",
    "phone": "0987654321"
}

### Get all plans
GET https://fastagtracking.com/customulip/plans

### Login
POST https://fastagtracking.com/customulip/login
Content-Type: application/json

{
    "phone": "1234567890",
    "password": "password"
}

### Delete a specific company by ID
DELETE https://fastagtracking.com/customulip/company/{company_id}

### ULIP API
POST https://fastagtracking.com/customulip/ulipApi
Content-Type: application/json

{
    "company_id": "66b2f12abbef97c004389b88",
    "tracking_For": "SARATHI",
    "parameters": { 
        "dlnumber": "AP03020190043439",
    "dob": "1980-09-10"
    }
}